{
 "title": "Air",
 "time": { "from": "2013-04-20T02:12:10.296Z", "to": "2015-10-13T13:48:49.640Z" },
 "panels": [
  {
   "title": "Average PM2.5 by Month",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "7d" ], "type": "time" },
      { "params": [ "city" ], "type": "tag" }
     ],
     "measurement": "pm2.5",
     "query": "SELECT mean(\"pm\") as res FROM \"pm\" WHERE $timeFilter GROUP BY time(4w), \"city\"",
     "select": [
      [
       { "params": [ "pm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Negative Correlation of Humidity and PM2.5",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "168h" ], "type": "time" },
      { "params": [ "city" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "pm",
     "query": "SELECT mean(\"humidity\") AS \"Humidity\" FROM \"pm\" WHERE $timeFilter GROUP BY time(4w), \"city\" fill(0)",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "Humidity" ], "type": "alias" }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"pm\") FROM \"pm\" WHERE $timeFilter GROUP BY time(4w), \"city\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Negative Correlation of Wind and PM2.5",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"pm\") FROM \"pm\" WHERE $timeFilter GROUP BY time(6h), \"city\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"wind_speed\") FROM \"pm\" WHERE $timeFilter GROUP BY time(6h), \"city\" fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}